/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class AllCoursesGUI extends javax.swing.JFrame {
    private static int noc = EnterNumberOfCoursesGUI.getNoc();
    public  static Courses [] Allcourses  = new Courses[noc];
    private static int nolec;
    private static int nolab;
    private static int counterofcourses=0;
    private static int lecnoh, labnoh;
    private static String lecnameofroom,labnameofroom;

    public static Courses[] getAllcourses() {
        return Allcourses;
    }
    
    public static int getLabnoh() {
        return labnoh;
    }

    public static String getLabnameofroom() {
        return labnameofroom;
    }
    

    
    public static String getLecnameofroom() {
        return lecnameofroom;
    }
    
    
    public static int getCounterofcourses() {
        return counterofcourses;
    }

    
    public static int getNoc() {
        return noc;
    }

    public static int getNolec() {
        return nolec;
    }

    /**
     * Creates new form AllCoursesGUI
     */
    public static int getNolab() {    
        return nolab;
    }

    public AllCoursesGUI() {
        initComponents();
        for ( int i=0 ; i < EnterNumberOfRoomsGUI.getNor(); i++){
            if(AllRoomsGUI.Allrooms[i] instanceof ClassRoom)
                choosecourselecroomname_combobox.addItem(AllRoomsGUI.Allrooms[i].getName());
            if(AllRoomsGUI.Allrooms[i] instanceof Laboratory)
                choosecourselabroomname_combobox.addItem(AllRoomsGUI.Allrooms[i].getName());
        }
    }

    public static int getLecnoh() {
        return lecnoh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entercourseid_label = new javax.swing.JLabel();
        entercourseid_tf = new javax.swing.JTextField();
        entercourse_btn = new javax.swing.JButton();
        entercoursename_label = new javax.swing.JLabel();
        entercoursename_tf = new javax.swing.JTextField();
        entercoursenolec_tf = new javax.swing.JTextField();
        entercoursenolec_label = new javax.swing.JLabel();
        entercoursenolab_tf = new javax.swing.JTextField();
        entercoursenolab_label = new javax.swing.JLabel();
        entercourselecnoh_tf = new javax.swing.JTextField();
        entercourselecnoh_label = new javax.swing.JLabel();
        choosecourselecroomname_label = new javax.swing.JLabel();
        choosecourselecroomname_combobox = new javax.swing.JComboBox<>();
        choosecourselabroomname_combobox = new javax.swing.JComboBox<>();
        choosecourselabroomname_label = new javax.swing.JLabel();
        entercourselabnoh_tf = new javax.swing.JTextField();
        entercourselabnoh_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entercourseid_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        entercourseid_label.setText("Enter Course #1 ID:");

        entercourseid_tf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        entercourse_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        entercourse_btn.setText("Enter");
        entercourse_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entercourse_btnActionPerformed(evt);
            }
        });

        entercoursename_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        entercoursename_label.setText("Enter Course #1 Name:");

        entercoursename_tf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        entercoursenolec_tf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        entercoursenolec_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        entercoursenolec_label.setText("Enter Course #1 Number of Lectures:");

        entercoursenolab_tf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        entercoursenolab_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entercoursenolab_tfActionPerformed(evt);
            }
        });

        entercoursenolab_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        entercoursenolab_label.setText("Enter Course #1 Number of Labs:");

        entercourselecnoh_tf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        entercourselecnoh_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entercourselecnoh_tfActionPerformed(evt);
            }
        });

        entercourselecnoh_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        entercourselecnoh_label.setText("Enter Course #1 Lecture Number of Hours:");

        choosecourselecroomname_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        choosecourselecroomname_label.setText("Choose Course #1 Lectures Room Name:");

        choosecourselecroomname_combobox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        choosecourselecroomname_combobox.setMaximumRowCount(20);
        choosecourselecroomname_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosecourselecroomname_comboboxActionPerformed(evt);
            }
        });

        choosecourselabroomname_combobox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        choosecourselabroomname_combobox.setMaximumRowCount(20);
        choosecourselabroomname_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosecourselabroomname_comboboxActionPerformed(evt);
            }
        });

        choosecourselabroomname_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        choosecourselabroomname_label.setText("Choose Course #1 Labs Room Name:");

        entercourselabnoh_tf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        entercourselabnoh_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entercourselabnoh_tfActionPerformed(evt);
            }
        });

        entercourselabnoh_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        entercourselabnoh_label.setText("Enter Course #1 Lab Number of Hours:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(entercourseid_label))
                    .addComponent(entercourseid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entercoursename_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(entercoursename_label)))
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entercourselecnoh_label)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(entercourselecnoh_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(entercourselabnoh_label)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(entercourselabnoh_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entercoursenolec_label)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(entercoursenolab_label)
                                    .addComponent(entercoursenolab_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entercoursenolec_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(choosecourselecroomname_label)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(choosecourselabroomname_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(choosecourselabroomname_label))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(choosecourselecroomname_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(entercourse_btn)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entercourseid_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entercourseid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entercoursename_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entercoursename_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entercoursenolec_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entercoursenolec_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(choosecourselecroomname_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(choosecourselecroomname_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entercoursenolab_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entercoursenolab_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(choosecourselabroomname_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(choosecourselabroomname_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entercourselecnoh_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entercourselecnoh_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entercourselabnoh_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entercourselabnoh_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addComponent(entercourse_btn)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entercourse_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entercourse_btnActionPerformed
        boolean ex = false;
        int id=0;
        try{
            ex = false;
            id = Integer.valueOf(entercourseid_tf.getText());
            nolec = Integer.valueOf(entercoursenolec_tf.getText());
            nolab = Integer.valueOf(entercoursenolab_tf.getText());
            lecnoh = Integer.valueOf(entercourselecnoh_tf.getText());
            labnoh = Integer.valueOf(entercourselabnoh_tf.getText());
        }
        catch(NumberFormatException nfe){ 
            ex = true;                        
            JOptionPane.showMessageDialog(rootPane, "ID\nNumber Of Lectures\nNumber Of Labs\nNumber Of Hours\nAre All Integers!");

        }
        if(!ex){
            entercourseid_label.setText("Enter Course #"+(counterofcourses+2)+" ID:");
            entercoursename_label.setText("Enter Course #"+(counterofcourses+2)+" Name:");
            entercoursenolec_label.setText("Enter Course #"+(counterofcourses+2)+" Number of Lectures:");
            choosecourselecroomname_label.setText("Enter Course #"+(counterofcourses+2)+" Lecture Room Name:");
            entercoursenolab_label.setText("Enter Course #"+(counterofcourses+2)+" Number of Labs:");
            choosecourselabroomname_label.setText("Enter Course #"+(counterofcourses+2)+" Lab Room Name:");
            entercourselecnoh_label.setText("Enter Course #"+(counterofcourses+2)+" Lecture Number of Hours:");
            entercourselabnoh_label.setText("Enter Course #"+(counterofcourses+2)+" Lab Number of Hours:");



            //int id = Integer.valueOf(entercourseid_tf.getText());  
            String name =entercoursename_tf.getText();

            
            lecnameofroom = choosecourselecroomname_combobox.getSelectedItem().toString();
            labnameofroom = choosecourselabroomname_combobox.getSelectedItem().toString();

            Allcourses[counterofcourses++] = new Courses(id,name,nolec,nolab);

            if(counterofcourses==noc){
                this.setVisible(false);
            }
            AllLecsGUI alllecsFrame = new AllLecsGUI();
            alllecsFrame.setVisible(true);

            entercourseid_tf.setText("");
            entercoursename_tf.setText("");
            entercoursenolec_tf.setText("");
            entercoursenolab_tf.setText("");
            entercourselecnoh_tf.setText("");
            entercourselabnoh_tf.setText("");
            choosecourselecroomname_combobox.setSelectedIndex(0);
            choosecourselabroomname_combobox.setSelectedIndex(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_entercourse_btnActionPerformed

    private void entercoursenolab_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entercoursenolab_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entercoursenolab_tfActionPerformed

    private void entercourselecnoh_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entercourselecnoh_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entercourselecnoh_tfActionPerformed

    private void choosecourselecroomname_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosecourselecroomname_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choosecourselecroomname_comboboxActionPerformed

    private void choosecourselabroomname_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosecourselabroomname_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choosecourselabroomname_comboboxActionPerformed

    private void entercourselabnoh_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entercourselabnoh_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entercourselabnoh_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllCoursesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllCoursesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllCoursesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllCoursesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllCoursesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> choosecourselabroomname_combobox;
    private javax.swing.JLabel choosecourselabroomname_label;
    private javax.swing.JComboBox<String> choosecourselecroomname_combobox;
    private javax.swing.JLabel choosecourselecroomname_label;
    private javax.swing.JButton entercourse_btn;
    private javax.swing.JLabel entercourseid_label;
    private javax.swing.JTextField entercourseid_tf;
    private javax.swing.JLabel entercourselabnoh_label;
    private javax.swing.JTextField entercourselabnoh_tf;
    private javax.swing.JLabel entercourselecnoh_label;
    private javax.swing.JTextField entercourselecnoh_tf;
    private javax.swing.JLabel entercoursename_label;
    private javax.swing.JTextField entercoursename_tf;
    private javax.swing.JLabel entercoursenolab_label;
    private javax.swing.JTextField entercoursenolab_tf;
    private javax.swing.JLabel entercoursenolec_label;
    private javax.swing.JTextField entercoursenolec_tf;
    // End of variables declaration//GEN-END:variables
}
