/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class AllLabsGUI extends javax.swing.JFrame {

    private static int nolab ;
   
    private static int counteroflabs;
    
    /**
     * Creates new form AllLecsGUI
     */
    public AllLabsGUI() {
        initComponents();
        
        nolab = AllCoursesGUI.getNolab();
        counteroflabs=0;
        enterlabtaid_label.setText(   "Enter Lab #1 of Course #"+(AllCoursesGUI.getCounterofcourses())+" TA ID:");
            enterlabtaname_label.setText( "Enter Lab #1 of Course #"+(AllCoursesGUI.getCounterofcourses())+" TA Name:");
            enterlabtaphone_label.setText("Enter Lab #1 of Course #"+(AllCoursesGUI.getCounterofcourses())+" TA Phone:");
            enterlabtaemail_label.setText("Enter Lab #1 of Course #"+(AllCoursesGUI.getCounterofcourses())+" TA Email:");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterlabtaid_label = new javax.swing.JLabel();
        enterlabtaid_tf = new javax.swing.JTextField();
        enterlabtaname_label = new javax.swing.JLabel();
        enterlabtaname_tf = new javax.swing.JTextField();
        enterlabtaphone_label = new javax.swing.JLabel();
        enterlabtaphone_tf = new javax.swing.JTextField();
        enterlabtaemail_label = new javax.swing.JLabel();
        enterlabtaemail_tf = new javax.swing.JTextField();
        enterlab_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enterlabtaid_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enterlabtaid_label.setText("Enter Lab #1 of Course #1 TA ID:");

        enterlabtaid_tf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        enterlabtaname_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enterlabtaname_label.setText("Enter Lab #1 of Course #1 TA Name:");

        enterlabtaname_tf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        enterlabtaphone_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enterlabtaphone_label.setText("Enter Lab #1 of Course #1 TA Phone:");

        enterlabtaphone_tf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        enterlabtaemail_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enterlabtaemail_label.setText("Enter Lab #1 of Course #1 TA Email:");

        enterlabtaemail_tf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enterlabtaemail_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterlabtaemail_tfActionPerformed(evt);
            }
        });

        enterlab_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enterlab_btn.setText("Enter");
        enterlab_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterlab_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enterlabtaname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterlabtaphone_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterlabtaid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterlabtaid_label))
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(enterlabtaemail_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(enterlab_btn)
                        .addGap(238, 238, 238))))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterlabtaemail_label)
                    .addComponent(enterlabtaphone_label)
                    .addComponent(enterlabtaname_label))
                .addGap(0, 131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(enterlabtaid_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterlabtaid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterlabtaname_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterlabtaname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterlabtaphone_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterlabtaphone_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enterlabtaemail_label)
                .addGap(11, 11, 11)
                .addComponent(enterlabtaemail_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enterlab_btn)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterlabtaemail_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterlabtaemail_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterlabtaemail_tfActionPerformed

    private void enterlab_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterlab_btnActionPerformed
        boolean ex = false;
        int TeacherID=0;
        try{
            ex=false;
            TeacherID = Integer.valueOf(enterlabtaid_tf.getText());
 

        }
        catch(NumberFormatException nfe){
            ex = true;                        
            JOptionPane.showMessageDialog(rootPane, "TA ID is an Integer!");

        }
        if(!ex){
            enterlabtaid_label.setText("Enter Lab #"+(counteroflabs+2)+" of Course #"+(AllCoursesGUI.getCounterofcourses()   )+" TA ID:");
            enterlabtaname_label.setText("Enter Lab #"+(counteroflabs+2)+" of Course #"+(AllCoursesGUI.getCounterofcourses() )+" TA Name:");
            enterlabtaphone_label.setText("Enter Lab #"+(counteroflabs+2)+" of Course #"+(AllCoursesGUI.getCounterofcourses())+" TA Phone:");
            enterlabtaemail_label.setText("Enter Lab #"+(counteroflabs+2)+" of Course #"+(AllCoursesGUI.getCounterofcourses())+" TA Email:");



            String name = enterlabtaname_tf.getText(); 
            String phone = enterlabtaphone_tf.getText();
            String email = enterlabtaemail_tf.getText();
            int numOfHrs = AllCoursesGUI.getLabnoh();
            String nameOfRoom = AllCoursesGUI.getLabnameofroom();

            AllCoursesGUI.Allcourses[AllCoursesGUI.getCounterofcourses()-1].getLabs()[counteroflabs++] = new Lab(TeacherID,name,phone,email,numOfHrs,nameOfRoom);


            if(counteroflabs==nolab){
                this.setVisible(false);

                counteroflabs=0;
                if(AllCoursesGUI.getNoc()== AllCoursesGUI.getCounterofcourses()){

                    OOPProject ooppro = new OOPProject();
                    System.exit(0);

                }
            }


            enterlabtaid_tf.setText("");
            enterlabtaname_tf.setText("");
            enterlabtaphone_tf.setText("");
            enterlabtaemail_tf.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_enterlab_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllLabsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllLabsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllLabsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllLabsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllLabsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterlab_btn;
    private javax.swing.JLabel enterlabtaemail_label;
    private javax.swing.JTextField enterlabtaemail_tf;
    private javax.swing.JLabel enterlabtaid_label;
    private javax.swing.JTextField enterlabtaid_tf;
    private javax.swing.JLabel enterlabtaname_label;
    private javax.swing.JTextField enterlabtaname_tf;
    private javax.swing.JLabel enterlabtaphone_label;
    private javax.swing.JTextField enterlabtaphone_tf;
    // End of variables declaration//GEN-END:variables
}
