/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopproject;
/**
 *
 * @author Lenovo
 */
public class AllRoomsGUI extends javax.swing.JFrame {
    private int counterofrooms =0;
    static private int nor = EnterNumberOfRoomsGUI.getNor();
    static public Rooms [] Allrooms = new Rooms[nor];
    /**
     * Creates new form AllRoomsGUI
     */
    public AllRoomsGUI() {
        initComponents();
        classroom_rad_btn.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rooms_rad_btn_grp = new javax.swing.ButtonGroup();
        enterroomname_label = new javax.swing.JLabel();
        enterroomname_tf = new javax.swing.JTextField();
        enterroomname_btn = new javax.swing.JButton();
        laboratory_rad_btn = new javax.swing.JRadioButton();
        classroom_rad_btn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enterroomname_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enterroomname_label.setText("Enter Room #1 Name:");

        enterroomname_tf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        enterroomname_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enterroomname_btn.setText("Enter");
        enterroomname_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterroomname_btnActionPerformed(evt);
            }
        });

        rooms_rad_btn_grp.add(laboratory_rad_btn);
        laboratory_rad_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        laboratory_rad_btn.setText("Laboratory");
        laboratory_rad_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratory_rad_btnActionPerformed(evt);
            }
        });

        rooms_rad_btn_grp.add(classroom_rad_btn);
        classroom_rad_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        classroom_rad_btn.setText("Classroom");
        classroom_rad_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classroom_rad_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(enterroomname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(102, 102, 102)
                                    .addComponent(enterroomname_btn)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(classroom_rad_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(laboratory_rad_btn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(enterroomname_label)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laboratory_rad_btn)
                    .addComponent(classroom_rad_btn))
                .addGap(18, 18, 18)
                .addComponent(enterroomname_label)
                .addGap(18, 18, 18)
                .addComponent(enterroomname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enterroomname_btn)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterroomname_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterroomname_btnActionPerformed
        enterroomname_label.setText("Enter Room #"+(counterofrooms+2)+" Name:");
        
        if(classroom_rad_btn.isSelected())
            Allrooms[counterofrooms++] = new ClassRoom(enterroomname_tf.getText());
        if(laboratory_rad_btn.isSelected())
            Allrooms[counterofrooms++] = new Laboratory(enterroomname_tf.getText());
         
        laboratory_rad_btn.setSelected(false);
        classroom_rad_btn.setSelected(true);
        enterroomname_tf.setText("");
        
        if(counterofrooms==nor){
        this.setVisible(false);
        EnterNumberOfCoursesGUI enternumberofcoursesFrame = new EnterNumberOfCoursesGUI();
        enternumberofcoursesFrame.setVisible(true);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_enterroomname_btnActionPerformed

    private void classroom_rad_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classroom_rad_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classroom_rad_btnActionPerformed

    private void laboratory_rad_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratory_rad_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laboratory_rad_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllRoomsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllRoomsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllRoomsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllRoomsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new AllRoomsGUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton classroom_rad_btn;
    private javax.swing.JButton enterroomname_btn;
    private javax.swing.JLabel enterroomname_label;
    private javax.swing.JTextField enterroomname_tf;
    private javax.swing.JRadioButton laboratory_rad_btn;
    private javax.swing.ButtonGroup rooms_rad_btn_grp;
    // End of variables declaration//GEN-END:variables
}
