/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class EnterNumberOfCoursesGUI extends javax.swing.JFrame {
    private static int noc;
    /**
     * Creates new form EnterNumberOfCoursesGUI
     */
    public EnterNumberOfCoursesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enternumberofrooms_label = new javax.swing.JLabel();
        enternumberofrooms_tf = new javax.swing.JTextField();
        enternumberofrooms_btn = new javax.swing.JButton();
        enternumberofcourses_label = new javax.swing.JLabel();
        enternumberofcourses_tf = new javax.swing.JTextField();
        enternumberofcourses_btn = new javax.swing.JButton();

        enternumberofrooms_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enternumberofrooms_label.setText("Enter Number Of Rooms:");

        enternumberofrooms_tf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        enternumberofrooms_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enternumberofrooms_btn.setText("Enter");
        enternumberofrooms_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enternumberofrooms_btnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enternumberofcourses_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enternumberofcourses_label.setText("Enter Number Of Courses:");

        enternumberofcourses_tf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enternumberofcourses_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enternumberofcourses_tfActionPerformed(evt);
            }
        });

        enternumberofcourses_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enternumberofcourses_btn.setText("Enter");
        enternumberofcourses_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enternumberofcourses_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(enternumberofcourses_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(enternumberofcourses_btn)
                        .addGap(236, 236, 236))))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(enternumberofcourses_label)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(enternumberofcourses_label)
                .addGap(30, 30, 30)
                .addComponent(enternumberofcourses_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(enternumberofcourses_btn)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enternumberofrooms_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enternumberofrooms_btnActionPerformed
   
    }//GEN-LAST:event_enternumberofrooms_btnActionPerformed

    public static int getNoc() {
        return noc;
    }

    private void enternumberofcourses_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enternumberofcourses_btnActionPerformed
        // TODO add your handling code here:
        boolean ex;
        try{
            ex=false;
            noc = Integer.valueOf(enternumberofcourses_tf.getText());

        }
        catch(NumberFormatException nfe){
            ex=true;
            JOptionPane.showMessageDialog(rootPane, "Please Enter an Integer");

        }
        if(!ex){
            this.setVisible(false);
            AllCoursesGUI entercoursesFrame = new AllCoursesGUI();
            entercoursesFrame.setVisible(true);
        }
    }//GEN-LAST:event_enternumberofcourses_btnActionPerformed

    private void enternumberofcourses_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enternumberofcourses_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enternumberofcourses_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterNumberOfCoursesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterNumberOfCoursesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterNumberOfCoursesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterNumberOfCoursesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterNumberOfCoursesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enternumberofcourses_btn;
    private javax.swing.JLabel enternumberofcourses_label;
    private javax.swing.JTextField enternumberofcourses_tf;
    private javax.swing.JButton enternumberofrooms_btn;
    private javax.swing.JLabel enternumberofrooms_label;
    private javax.swing.JTextField enternumberofrooms_tf;
    // End of variables declaration//GEN-END:variables
}
